name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Match Angular LTS version

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore .NET dependencies
        run: dotnet restore CICDTestProject/CICDTestProject.csproj

      - name: Install Angular dependencies
        working-directory: CICDTestProject/CICDTestProject/ClientApp
        run: npm install

      - name: Build Angular project
        working-directory: CICDTestProject/CICDTestProject/ClientApp
        run: npm run build -- --configuration production

      - name: Publish .NET project
        run: dotnet publish CICDTestProject/CICDTestProject.csproj -c Release -o ./publish

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: /www.CICDTest.somee.com/
