name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean server folder
        run: |
          echo "open ${{secrets.FTP_SERVER}}
          user ${{secrets.FTP_USERNAME}} ${{secrets.FTP_PASSWORD}}
          mirror -R --delete --only-newer --verbose publish/ /www.CICDTest.somee.com/" > ftpcmd.txt
          ftp -n -s:ftpcmd.txt
        shell: cmd

      # 9. FTP Deploy everything
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          local-dir: publish/             # upload the CONTENTS of publish (no trailing slash)
          server-dir: 'www.CICDTest.somee.com/'                # <-- fixed: use server path ('.' = home directory)
          protocol: ftp
